###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Idempotency",
  "author": "Fareed",
  "url": "https://linkedin/fareed-mohammed/idempotency",
  "likes": 200
}

###
GET http://localhost:3001/api/blogs
